name: Deploy Site

on:
  push:
    tags: # Deploy tag (e.g. v1.0) to production
      - 'v**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Replace 'Steedos' with 'FindBuild' in docs & i18n Folder
        run: |
          find docs i18n -type f \( -name "*.md" -o -name "*.mdx" -o -name "*.json" -o -name "*.yml" \) -exec sed -i 's/Steedos/FineBuild/g' {} +
          rm -rf docs/getting-started/user
          rm -rf docs/deploy
          rm -rf i18n/zh-CN/docusaurus-plugin-content-docs/current/getting-started/user
          rm -rf i18n/zh-CN/docusaurus-plugin-content-docs/current/deploy

      - name: Build Docusaurus site
        run: yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: cn-northwest-1

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: finebuild-docs
          AWS_S3_REGION: cn-northwest-1
          SOURCE_DIR: ./build/
